<?php
/** @var CView $this */
?>
<div style="margin: 20px;">
    <div style="background-color: #fff; border: 1px solid #dfe4e8; border-radius: 2px; padding: 30px; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
        <h1 style="color: #1f2c33; margin-top: 0; font-family: Arial, sans-serif;"><?php echo $data['message']; ?></h1>
        <hr style="border: 0; border-top: 1px solid #ebeef0; margin: 20px 0;">
        <p style="color: #4f5355; font-size: 14px; line-height: 1.6;">
            This page is generated by a custom Zabbix module.<br>
            Current Status: <strong>Monitoring Active</strong>
        </p>
    </div>
</div>
